Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -58,47 +58,46 @@ jobs:
     runs-on: ubuntu-latest
     environment: production
 
-    # Use the Bash shell regardless of whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
     defaults:
       run:
         shell: bash
 
     steps:
-    # Checkout the repository to the GitHub Actions runner
     - name: Checkout
       uses: actions/checkout@v4
 
-    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
     - name: Log in to Azure
       uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_SECRETS }}
+
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: '3.11'  # Set up Python version 3.11
 
     - name: Set up Terraform
       uses: hashicorp/setup-terraform@v1
       with:
         terraform_version: 1.0.0
 
-    # Install Checkov
+    # Install Checkov and verify installation
     - name: Install Checkov
       run: |
-       python -m pip install --upgrade pip
-       pip install checkov
-       checkov --version  # Check if Checkov is installed correctly
+        python -m pip install --upgrade pip
+        pip install checkov
+        checkov --version  # Verify Checkov is installed
 
-
-    # Run Checkov to scan the Terraform code for security issues or misconfigurations
+    # Run Checkov to scan the Terraform code
     - name: Run Checkov (Terraform Code Scan)
-      run: checkov -d .  # This will scan all the Terraform code in the repository
+      run: |
+        checkov -d . || (echo "Checkov failed to scan" && exit 1)  # Fail gracefully and print error if Checkov fails
 
-    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
     - name: Terraform Init
       run: terraform init
 
-    # Generates an execution plan for Terraform
     - name: Terraform Plan
       run: terraform plan -input=false
 
-    # Apply the Terraform configuration
     - name: Terraform Apply
       run: terraform apply -auto-approve -input=false
